apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: jassbot-challenge.playground.int-test.netcetera.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jassbot-challenge-server-svc
                port:
                  number: 80